"""make telegram_id nullable

Revision ID: f231678720fb
Revises: 
Create Date: 2025-03-07 11:45:35.658806+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f231678720fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Make telegram_id nullable
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)


def downgrade() -> None:
    # Revert telegram_id to non-nullable
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processing_results_message_id', table_name='processing_results')
    op.drop_table('processing_results')
    op.drop_index('idx_messages_date', table_name='messages')
    op.drop_index('idx_messages_dialog_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('migrations')
    op.drop_index('idx_queue_tasks_dialog_id', table_name='queue_tasks')
    op.drop_index('idx_queue_tasks_message_id', table_name='queue_tasks')
    op.drop_index('idx_queue_tasks_priority', table_name='queue_tasks')
    op.drop_index('idx_queue_tasks_scheduled_for', table_name='queue_tasks')
    op.drop_index('idx_queue_tasks_status', table_name='queue_tasks')
    op.drop_index('idx_queue_tasks_telegram_id', table_name='queue_tasks')
    op.drop_table('queue_tasks')
    op.drop_constraint('uq_processed_response_dialog', 'processed_responses', type_='unique')
    op.create_unique_constraint('uq_dialog_response', 'processed_responses', ['dialog_id'])
    # ### end Alembic commands ### 