"""
API Router for managing AI-generated responses

This module provides endpoints for retrieving, reviewing, and managing
responses generated by the AI processor.
"""

from fastapi import APIRouter, HTTPException, status, Depends, Query
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, UUID4
from datetime import datetime
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import joinedload

from app.middleware import verify_session
from app.middleware.session import SessionData
from app.db.database import get_db
from app.db.models.processed_response import ProcessedResponse
from app.db.models.dialog import Dialog
from app.db.models.types import ProcessingStatus
from app.utils.logging import get_logger
from app.services.response_sender import ResponseSender
from app.services.telegram import get_recent_messages
from app.db.models.message import Message
from app.api.messages import list_dialog_messages
from app.services.llm_api import query_llm

router = APIRouter(tags=["responses"])
logger = get_logger(__name__)

# Response models
class ResponseBase(BaseModel):
    """Base model for response data"""
    id: UUID4
    dialog_id: UUID4
    last_message_id: str
    suggested_response: str
    edited_response: Optional[str] = None
    status: str
    model_name: str
    processed_at: datetime
    
    class Config:
        from_attributes = True

class ResponseWithDialog(ResponseBase):
    """Response model with dialog information"""
    dialog_name: str
    last_message_timestamp: datetime

class ResponseUpdate(BaseModel):
    """Model for updating a response"""
    edited_response: str

class ResponseList(BaseModel):
    """Response model for list of responses"""
    responses: List[ResponseWithDialog]
    total: int

class GenerateRequest(BaseModel):
    """Request model for generating responses"""
    telegram_dialog_id: str

@router.get(
    "/pending",
    response_model=ResponseList,
    summary="Get pending responses",
    description="Get all responses with PENDING_APPROVAL status. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def get_pending_responses(
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db),
    skip: int = Query(0, ge=0),
    limit: int = Query(10, ge=1, le=100)
):
    """
    Get all pending responses for the authenticated user
    
    Args:
        session: Session data from authentication
        db: Database session
        skip: Number of items to skip for pagination
        limit: Maximum number of items to return
        
    Returns:
        List of pending responses with dialog information
    """
    try:
        # Get all pending responses for the user's dialogs
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                Dialog.user_id == session.user_id,
                ProcessedResponse.status == ProcessingStatus.PENDING_APPROVAL
            )
            .options(joinedload(ProcessedResponse.dialog))
            .order_by(ProcessedResponse.processed_at.desc())
            .offset(skip)
            .limit(limit)
        )
        
        # Execute query
        result = await db.execute(query)
        responses = result.unique().scalars().all()
        
        # Get total count for pagination
        count_query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                Dialog.user_id == session.user_id,
                ProcessedResponse.status == ProcessingStatus.PENDING_APPROVAL
            )
        )
        count_result = await db.execute(count_query)
        total_count = len(count_result.unique().scalars().all())
        
        # Format responses with dialog information
        formatted_responses = []
        for response in responses:
            formatted_responses.append({
                "id": response.id,
                "dialog_id": response.dialog_id,
                "dialog_name": response.dialog.title,
                "last_message_id": response.last_message_id,
                "last_message_timestamp": response.last_message_timestamp,
                "suggested_response": response.suggested_response,
                "edited_response": response.edited_response,
                "status": response.status,
                "model_name": response.model_name,
                "processed_at": response.processed_at
            })
        
        return {
            "responses": formatted_responses,
            "total": total_count
        }
        
    except Exception as e:
        logger.error(f"Error getting pending responses: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve pending responses"
        )

@router.get(
    "/history",
    response_model=ResponseList,
    summary="Get response history",
    description="Get response history (approved, rejected, sent). Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def get_response_history(
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db),
    skip: int = Query(0, ge=0),
    limit: int = Query(10, ge=1, le=100),
    status_filter: Optional[str] = Query(None, description="Filter by status (approved, rejected, sent, failed)")
):
    """
    Get response history for the authenticated user
    
    Args:
        session: Session data from authentication
        db: Database session
        skip: Number of items to skip for pagination
        limit: Maximum number of items to return
        status_filter: Optional filter by status
        
    Returns:
        List of historical responses with dialog information
    """
    try:
        # Build base query
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(Dialog.user_id == session.user_id)
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        # Apply status filter if provided
        if status_filter:
            try:
                status_enum = ProcessingStatus(status_filter.lower())
                query = query.where(ProcessedResponse.status == status_enum)
            except ValueError:
                # Invalid status, ignore filter
                pass
        else:
            # If no filter, exclude pending responses (they're in the pending endpoint)
            query = query.where(ProcessedResponse.status != ProcessingStatus.PENDING_APPROVAL)
        
        # Add pagination and ordering
        query = (
            query
            .order_by(ProcessedResponse.updated_at.desc())
            .offset(skip)
            .limit(limit)
        )
        
        # Execute query
        result = await db.execute(query)
        responses = result.unique().scalars().all()
        
        # Get total count for pagination
        count_query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(Dialog.user_id == session.user_id)
        )
        
        # Apply same status filter to count query
        if status_filter:
            try:
                status_enum = ProcessingStatus(status_filter.lower())
                count_query = count_query.where(ProcessedResponse.status == status_enum)
            except ValueError:
                pass
        else:
            count_query = count_query.where(ProcessedResponse.status != ProcessingStatus.PENDING_APPROVAL)
            
        count_result = await db.execute(count_query)
        total_count = len(count_result.unique().scalars().all())
        
        # Format responses with dialog information
        formatted_responses = []
        for response in responses:
            formatted_responses.append({
                "id": response.id,
                "dialog_id": response.dialog_id,
                "dialog_name": response.dialog.title,
                "last_message_id": response.last_message_id,
                "last_message_timestamp": response.last_message_timestamp,
                "suggested_response": response.suggested_response,
                "edited_response": response.edited_response,
                "status": response.status,
                "model_name": response.model_name,
                "processed_at": response.processed_at
            })
        
        return {
            "responses": formatted_responses,
            "total": total_count
        }
        
    except Exception as e:
        logger.error(f"Error getting response history: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve response history"
        )

@router.get(
    "/{response_id}",
    response_model=ResponseWithDialog,
    summary="Get response by ID",
    description="Get a specific response by ID. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Response not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def get_response(
    response_id: UUID4,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Get a specific response by ID
    
    Args:
        response_id: ID of the response to retrieve
        session: Session data from authentication
        db: Database session
        
    Returns:
        Response with dialog information
    """
    try:
        # Get response with dialog information
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                ProcessedResponse.id == response_id,
                Dialog.user_id == session.user_id
            )
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        result = await db.execute(query)
        response = result.unique().scalar_one_or_none()
        
        if not response:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Response not found"
            )
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": response.dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting response {response_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve response"
        )

@router.put(
    "/{response_id}",
    response_model=ResponseWithDialog,
    summary="Update response",
    description="Update a response with edited text. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Response not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def update_response(
    response_id: UUID4,
    response_update: ResponseUpdate,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Update a response with edited text
    
    Args:
        response_id: ID of the response to update
        response_update: Updated response data
        session: Session data from authentication
        db: Database session
        
    Returns:
        Updated response with dialog information
    """
    try:
        # Get response with dialog information
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                ProcessedResponse.id == response_id,
                Dialog.user_id == session.user_id
            )
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        result = await db.execute(query)
        response = result.unique().scalar_one_or_none()
        
        if not response:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Response not found"
            )
        
        # Update response
        response.edited_response = response_update.edited_response
        await db.commit()
        await db.refresh(response)
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": response.dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating response {response_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update response"
        )

@router.post(
    "/{response_id}/approve",
    response_model=ResponseWithDialog,
    summary="Approve response",
    description="Approve a response for sending. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Response not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def approve_response(
    response_id: UUID4,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Approve a response for sending
    
    Args:
        response_id: ID of the response to approve
        session: Session data from authentication
        db: Database session
        
    Returns:
        Approved response with dialog information
    """
    try:
        # Get response with dialog information
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                ProcessedResponse.id == response_id,
                Dialog.user_id == session.user_id
            )
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        result = await db.execute(query)
        response = result.unique().scalar_one_or_none()
        
        if not response:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Response not found"
            )
        
        # Update response status
        response.status = ProcessingStatus.APPROVED
        response.approved_at = datetime.utcnow()
        await db.commit()
        await db.refresh(response)
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": response.dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error approving response {response_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to approve response"
        )

@router.post(
    "/{response_id}/reject",
    response_model=ResponseWithDialog,
    summary="Reject response",
    description="Reject a response. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Response not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def reject_response(
    response_id: UUID4,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Reject a response
    
    Args:
        response_id: ID of the response to reject
        session: Session data from authentication
        db: Database session
        
    Returns:
        Rejected response with dialog information
    """
    try:
        # Get response with dialog information
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                ProcessedResponse.id == response_id,
                Dialog.user_id == session.user_id
            )
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        result = await db.execute(query)
        response = result.unique().scalar_one_or_none()
        
        if not response:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Response not found"
            )
        
        # Update response status
        response.status = ProcessingStatus.REJECTED
        await db.commit()
        await db.refresh(response)
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": response.dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error rejecting response {response_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to reject response"
        )

@router.post(
    "/{response_id}/send",
    response_model=ResponseWithDialog,
    summary="Send approved response",
    description="Send an approved response to Telegram. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Response not found"},
        422: {"description": "Response is not approved"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def send_response(
    response_id: UUID4,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Send an approved response to Telegram
    
    Args:
        response_id: ID of the response to send
        session: Session data from authentication
        db: Database session
        
    Returns:
        Sent response with dialog information
    """
    try:
        # Get response with dialog information
        query = (
            select(ProcessedResponse)
            .join(Dialog, ProcessedResponse.dialog_id == Dialog.id)
            .where(
                ProcessedResponse.id == response_id,
                Dialog.user_id == session.user_id
            )
            .options(joinedload(ProcessedResponse.dialog))
        )
        
        result = await db.execute(query)
        response = result.unique().scalar_one_or_none()
        
        if not response:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Response not found"
            )
        
        # Check if response is approved
        if response.status != ProcessingStatus.APPROVED:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Response must be approved before sending"
            )
        
        # Send the response
        response_sender = ResponseSender()
        success = await response_sender.send_response(str(response_id), db)
        
        if not success:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to send response to Telegram"
            )
        
        # Refresh the response to get updated status
        await db.refresh(response)
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": response.dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error sending response {response_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to send response"
        )

@router.post(
    "/generate/private",
    response_model=ResponseWithDialog,
    summary="Generate response for private chat",
    description="Generate AI response for a private chat dialog. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Dialog not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def generate_private_chat_response(
    request: GenerateRequest,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Generate response for a private chat dialog
    
    Args:
        request: Generate request with dialog ID
        session: Session data from authentication
        db: Database session
        
    Returns:
        Generated response with dialog information
    """
    return await _generate_response(request.telegram_dialog_id, session, db, is_group=False)

@router.post(
    "/generate/group",
    response_model=ResponseWithDialog,
    summary="Generate response for group chat",
    description="Generate AI response for a group chat dialog. Requires authentication.",
    responses={
        401: {"description": "Invalid or expired session"},
        403: {"description": "Not authenticated"},
        404: {"description": "Dialog not found"}
    },
    openapi_extra={
        "security": [{"BearerAuth": []}]
    }
)
async def generate_group_chat_response(
    request: GenerateRequest,
    session: SessionData = Depends(verify_session),
    db: AsyncSession = Depends(get_db)
):
    """
    Generate response for a group chat dialog
    
    Args:
        request: Generate request with dialog ID
        session: Session data from authentication
        db: Database session
        
    Returns:
        Generated response with dialog information
    """
    return await _generate_response(request.telegram_dialog_id, session, db, is_group=True)

async def _generate_response(
    telegram_dialog_id: str,
    session: SessionData,
    db: AsyncSession,
    is_group: bool
) -> Dict[str, Any]:
    """
    Shared logic for generating responses for both private and group chats
    
    Args:
        telegram_dialog_id: Telegram ID of the dialog to generate response for
        session: Session data from authentication
        db: Database session
        is_group: Whether this is a group chat (for future differentiation)
        
    Returns:
        Generated response with dialog information
    """
    try:
        # Get dialog and validate ownership
        query = (
            select(Dialog)
            .where(
                Dialog.telegram_dialog_id == telegram_dialog_id,
                Dialog.user_id == session.user_id
            )
        )
        result = await db.execute(query)
        dialog = result.scalar_one_or_none()
        
        if not dialog:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Dialog not found"
            )

        # TODO: Investigate Telethon's iter_messages parameters to:
        # 1. Find the first unread message
        # 2. Fetch N messages before that point for better context
        # 3. Consider using dialog.unread_count to optimize fetching
        # For now, we'll fetch the most recent 50 messages
        messages = await get_recent_messages(
            token=session.token,
            limit=50,
            dialog_id=int(telegram_dialog_id)
        )
        
        if not messages:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="No messages found in dialog"
            )

        # Convert raw messages to our Message model
        processed_messages = []
        for msg in messages:
            processed_messages.append(Message(
                telegram_message_id=str(msg['message_id']),
                dialog_id=telegram_dialog_id,
                text=msg['text'],
                sender_id=str(msg['sender']['id']),
                sender_name=msg['sender'].get('name', 'Unknown'),
                date=datetime.fromisoformat(msg['date']),
                is_outgoing=msg.get('is_outgoing', False)
            ))

        # Generate AI response
        # TODO: Pass is_group to the AI service when implementing different behaviors
        response_text = await generate_ai_response(processed_messages, dialog)
        
        # Create or update response in database
        # Since UI is locked during generation, we can safely overwrite any existing response
        query = (
            select(ProcessedResponse)
            .where(ProcessedResponse.dialog_id == dialog.id)
        )
        result = await db.execute(query)
        existing_response = result.scalar_one_or_none()
        
        last_message = processed_messages[-1]
        
        if existing_response:
            # Update existing response
            existing_response.suggested_response = response_text
            existing_response.status = ProcessingStatus.PENDING_APPROVAL
            existing_response.last_message_id = last_message.telegram_message_id
            existing_response.last_message_timestamp = last_message.date
            existing_response.model_name = "gpt-4"  # TODO: Make configurable
            existing_response.processed_at = datetime.utcnow()
            response = existing_response
        else:
            # Create new response
            response = ProcessedResponse(
                dialog_id=dialog.id,
                suggested_response=response_text,
                status=ProcessingStatus.PENDING_APPROVAL,
                last_message_id=last_message.telegram_message_id,
                last_message_timestamp=last_message.date,
                model_name="gpt-4",  # TODO: Make configurable
                processed_at=datetime.utcnow()
            )
            db.add(response)
        
        await db.commit()
        await db.refresh(response)
        
        # Format response with dialog information
        return {
            "id": response.id,
            "dialog_id": response.dialog_id,
            "dialog_name": dialog.title,
            "last_message_id": response.last_message_id,
            "last_message_timestamp": response.last_message_timestamp,
            "suggested_response": response.suggested_response,
            "edited_response": response.edited_response,
            "status": response.status,
            "model_name": response.model_name,
            "processed_at": response.processed_at
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating response for dialog {telegram_dialog_id}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate response"
        )

async def generate_ai_response(messages: List[Message], dialog: Dialog) -> str:
    """
    Generate AI response for the given messages using LLM API
    
    Args:
        messages: List of messages to process
        dialog: Dialog information
        
    Returns:
        Generated response text
    """
    try:
        # Format messages into a conversation prompt
        prompt = f"You are having a conversation in a Telegram chat with {dialog.title}. Here are the recent messages:\n\n"
        
        for msg in messages:
            sender = "You" if msg.is_outgoing else msg.sender_name
            prompt += f"{sender}: {msg.text}\n"
        
        prompt += "\nPlease provide a natural and contextually appropriate response to continue this conversation."
        
        # Call LLM API
        response = query_llm(prompt, provider="anthropic")  # Using Claude for better conversation
        
        if not response:
            logger.error("Failed to get response from LLM API")
            return "I apologize, but I'm having trouble generating a response right now. Please try again later."
            
        return response.strip()
        
    except Exception as e:
        logger.error(f"Error generating AI response: {str(e)}", exc_info=True)
        return "I apologize, but I encountered an error while generating a response. Please try again later."